name: 'Daily Perf Improver Build Steps'
description: 'Build ONNX Runtime with performance testing and benchmarking capabilities'

inputs:
  build-config:
    description: 'Build configuration (Release, Debug, RelWithDebInfo)'
    default: 'Release'
  enable-cuda:
    description: 'Enable CUDA execution provider'
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install Python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install cmake ninja

    - name: Setup build environment
      shell: bash
      run: |
        echo "Setting up ONNX Runtime build environment"
        echo "Current directory: $(pwd)"
        echo "Python version: $(python --version)"
        echo "CMake version: $(cmake --version)"
        
    - name: Build ONNX Runtime with benchmarks
      shell: bash
      run: |
        # Build command based on research of CI workflows
        EXTRA_ARGS=""
        if [ "${{ inputs.enable-cuda }}" = "true" ]; then
          EXTRA_ARGS="--use_cuda"
        fi
        
        # Core build with benchmarks enabled for performance testing
        ./build.sh \
          --config ${{ inputs.build-config }} \
          --build_micro_benchmarks \
          --cmake_extra_defines onnxruntime_BUILD_BENCHMARKS=ON \
          --parallel \
          $EXTRA_ARGS

    - name: Verify build artifacts
      shell: bash
      run: |
        BUILD_DIR="build/Linux"
        echo "Checking build artifacts in $BUILD_DIR/${{ inputs.build-config }}/"
        
        # Check if main ONNX Runtime library exists
        if [ -f "$BUILD_DIR/${{ inputs.build-config }}/libonnxruntime.so" ]; then
          echo "✓ libonnxruntime.so found"
        else
          echo "✗ libonnxruntime.so not found"
        fi
        
        # Check if performance test binary exists
        if [ -f "$BUILD_DIR/${{ inputs.build-config }}/onnxruntime_perf_test" ]; then
          echo "✓ onnxruntime_perf_test found"
        else
          echo "✗ onnxruntime_perf_test not found"
        fi
        
        # Check if benchmark binary exists
        if [ -f "$BUILD_DIR/${{ inputs.build-config }}/onnxruntime_benchmark_executable" ]; then
          echo "✓ onnxruntime_benchmark_executable found"
        elif [ -f "$BUILD_DIR/${{ inputs.build-config }}/onnxruntime_benchmark" ]; then
          echo "✓ onnxruntime_benchmark found"
        else
          echo "✗ Benchmark executable not found"
        fi
        
        echo "Build verification complete"

    - name: Setup performance testing environment
      shell: bash
      run: |
        echo "Setting up environment for performance testing and micro-benchmarking"
        
        # Add build directory to PATH for easy access to perf tools
        BUILD_DIR="$(pwd)/build/Linux/${{ inputs.build-config }}"
        echo "$BUILD_DIR" >> $GITHUB_PATH
        
        # Set environment variables for performance testing
        echo "ORT_BUILD_DIR=$BUILD_DIR" >> $GITHUB_ENV
        echo "ORT_CONFIG=${{ inputs.build-config }}" >> $GITHUB_ENV
        
        # Create a quick test to ensure the build works
        if [ -f "$BUILD_DIR/onnxruntime_perf_test" ]; then
          echo "Performance test binary is ready"
        else
          echo "Warning: Performance test binary not found"
        fi

    - name: Install Python performance tools
      shell: bash
      run: |
        # Install Python packages needed for performance benchmarking
        python -m pip install numpy
        
        # Check if transformer benchmarking tools are available
        if [ -d "onnxruntime/python/tools/transformers" ]; then
          echo "Transformer benchmarking tools found"
        fi
        
        if [ -d "onnxruntime/python/tools/microbench" ]; then
          echo "Microbench tools found"
        fi